server:
  port: 9099
  max-http-header-size: 552000
  servlet:
    encoding:
      force: true
      charset: UTF-8
  jetty:
    threads:
      min: 100
      max: 3000
      idle-timeout: 10000
    connection-idle-timeout: 10000
    accesslog:
      enabled: true


service:
  api:
    base-path: /services/spring-webservice-soap-client
  swagger:
    path: '/services/spring-webservice-soap-client-docs/v3/api-docs'
    title: 'spring-webservice-soap-client'
    version: 'version1.0.1-1401/03/17 00:40'
    description: 'spring-webservice-soap-client'
    host: 'localhost'
    api-gateway:
      host: 'localhost'
      port: 9096

  person-api:
    serviceUrl: https://localhost:9091/soapServices/personSoap
    disableHostnameCheck: true
    jksFile: keystore/person_api.jks
    jksPassword: saber@123
    username: saber66
    password: saber@123
    connectTimeout: 30000
    readTimeout: 30000
    connectionTimeToLive: 30000
    connectionPerRoute: 300
    maxTotalConnection: 3000


spring:
  application:
    name: spring-webservices-soap-client
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.webservices.WebServicesAutoConfiguration


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    display-operation-id: true
    persist-authorization: true
    operations-sorter: method
  oAuthFlow:
    authorizationUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/auth
    tokenUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true
  api-docs:
    path: ${service.swagger.path}


camel:
  springboot:
    main-run-controller: true
    jmx-management-statistics-level: extended
    endpoint-runtime-statistics-enabled: true
    jmx-enabled: true
  cloud:
    consul:
      service-host: localhost
      url: http://localhost:8500
      id: ${spring.application.name}
      registrationScheduled: 30000
    service-call:
      default-load-balancer: true

hawtio:
  authenticationEnabled: false
management:
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      sla:
        "[http.server.requests]": 10ms, 100ms
      percentiles:
        "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuators/webservice-soap-client
      exposure:
        include: '*'

