server:
  port: 9091
  servlet:
    encoding:
      force: true
      charset: UTF-8
  jetty:
    accesslog:
      enabled: true
    threads:
      max: 3000
      min: 300
      idle-timeout: 10000
    connection-idle-timeout: 10000
  max-http-header-size: 512000

  ssl:
    key-store-type: JKS
    key-store: classpath:keystore/person_api.jks
    key-store-password: saber@123
    key-alias: saber66
    enabled: true
    protocol: SSL

cxf:
  path: /soapServices
  endpoint: /personSoap
  endpointName: "personSoapApi"


spring:
  application:
    name: person-soap-service
  c3p0:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: saber66
    password: AdminSaber66
    minPoolSize: 10
    maxPoolSize: 20
    initialPoolSize: 10
    acquireIncrement: 4
    acquireRetryDelay: 600
    checkTimeout: 10000
    maxConnectionAge: 30
    maxIdleTimeout: 30
    maxStatementPerConnection: 100
    idleConnectionTestPeriod: 180
    testConnectionOnCheckout: false
    testConnectionOnCheckin: true
    numHelperThreads: 100
    preferredTestQuery: 'SELECT 1'
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true


camel:
  threadpool:
    pool-size: 1000
    max-pool-size: 3000
    max-queue-size: 2000
    rejected-policy: discardoldest
  springboot:
    jmx-management-statistics-level: extended
    backlog-tracing: true
  cloud:
    consul:
      service-host: localhost
      url: http://localhost:8500
      id: ${spring.application.name}
      registrationScheduled: 30000
    service-call:
      default-load-balancer: true
  dataformat:
    json-jackson:
      pretty-print: true
      auto-discover-object-mapper: true


hawtio:
  authenticationEnabled: false
management:
  metrics:
  distribution:
    percentiles-histogram:
      "[http.server.requests]": true
    sla:
      "[http.server.requests]": 10ms, 100ms
    percentiles:
      "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuators/person-soap-api
      exposure:
        include: '*'

