//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.03 at 06:03:18 PM IRDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.saber.spring_camel_cxf_soap_provider.soap.services/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.saber.spring.webservice.soap.client.dto.wsdl;
