//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.03 at 06:03:18 PM IRDT 
//


package com.saber.spring.webservice.soap.client.dto.wsdl;

import com.google.gson.GsonBuilder;
import com.google.gson.LongSerializationPolicy;
import com.google.gson.ToNumberPolicy;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for UpdatePersonByNationalCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdatePersonByNationalCode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nationalCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="personDto" type="{http://com.saber.spring_camel_cxf_soap_provider.soap.services/}PersonSoapDto"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdatePersonByNationalCode", namespace = "http://services.soap.spring_camel_cxf_soap_provider.saber.com/", propOrder = {
    "nationalCode",
    "personDto"
})
@XmlRootElement(name = "UpdatePersonByNationalCode", namespace = "http://services.soap.spring_camel_cxf_soap_provider.saber.com/")
public class UpdatePersonByNationalCode {

    @XmlElement(required = true, defaultValue = "")
    protected String nationalCode;
    @XmlElement(required = true)
    protected PersonSoapDto personDto;

    /**
     * Gets the value of the nationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalCode() {
        return nationalCode;
    }

    /**
     * Sets the value of the nationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalCode(String value) {
        this.nationalCode = value;
    }

    /**
     * Gets the value of the personDto property.
     * 
     * @return
     *     possible object is
     *     {@link PersonSoapDto }
     *     
     */
    public PersonSoapDto getPersonDto() {
        return personDto;
    }

    /**
     * Sets the value of the personDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonSoapDto }
     *     
     */
    public void setPersonDto(PersonSoapDto value) {
        this.personDto = value;
    }
    @Override
    public String toString() {
        return new GsonBuilder()
                .setLenient()
                .setPrettyPrinting()
                .enableComplexMapKeySerialization()
                .setLongSerializationPolicy(LongSerializationPolicy.DEFAULT)
                .setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE)
                .create().toJson(this, UpdatePersonByNationalCode.class);
    }
}
