server:
  port: 9096
  netty:
    connection-timeout: 10000
    idle-timeout: 10000
    threads: 3000
  max-http-request-header-size: 552000
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${management.endpoints.web.base-path}/health
        consistency-mode: consistent
        service-name: ${spring.application.name}
        hostname: localhost
    gateway:
      httpclient:
        pool:
          type: elastic
          max-idle-time: 10000
          max-connections: 5000
          max-life-time: 10000
        connect-timeout: 10000
        response-timeout: 30000
        max-header-size: 552000
      metrics:
        enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: person-soap-client
          uri: lb://person-soap-client
          predicates:
            - Path=/services/person-soap-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: person-soap-client-docs
          uri: lb://person-soap-client
          predicates:
            - Path=/services/person-soap-client-docs/v2/api-docs

        - id: spring-camel-rest-client
          uri: lb://spring-camel-rest-client
          predicates:
            - Path=/services/camel-rest-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: spring-camel-rest-client-docs
          uri: lb://spring-camel-rest-client
          predicates:
            - Path=/services/camel-rest-client/v3/api-docs


        - id: webflux-camel-rest-client
          uri: lb://webflux-camel-rest-client
          predicates:
            - Path=/services/webflux-camel-rest-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: webflux-camel-rest-client-docs
          uri: lb://webflux-camel-rest-client
          predicates:
            - Path=/services/webflux-camel-rest-client-docs/v3/api-docs


        - id: spring-webflux-rest-client
          uri: lb://spring-webflux-rest-client
          predicates:
            - Path=/services/webflux-rest-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: spring-webflux-rest-client-docs
          uri: lb://spring-webflux-rest-client
          predicates:
            - Path=/services/webflux-rest-client-docs/v3/api-docs

        - id: webflux-camel-soap-client
          uri: lb://webflux-camel-soap-client
          predicates:
            - Path=/services/webflux-camel-soap-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: webflux-camel-soap-client-docs
          uri: lb://webflux-camel-soap-client
          predicates:
            - Path=/services/webflux-camel-soap-client-docs/v3/api-docs

        - id: spring-rest-client
          uri: lb://spring-rest-client
          predicates:
            - Path=/services/spring-rest-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: spring-rest-client-docs
          uri: lb://spring-rest-client
          predicates:
            - Path=/services/spring-rest-client-docs/v3/api-docs
        - id: spring-webservices-soap-client
          uri: lb://spring-webservices-soap-client
          predicates:
            - Path=/services/spring-webservice-soap-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: spring-webservices-soap-client-docs
          uri: lb://spring-webservices-soap-client
          predicates:
            - Path=/services/spring-webservice-soap-client-docs/v3/api-docs

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/auth/realms/saber66
          jwk-set-uri: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    display-operation-id: true
    urls:
      - url: http://localhost:${server.port}/services/person-soap-client-docs/v2/api-docs
        name: 'spring camel soap client'
      - url: http://localhost:${server.port}/services/camel-rest-client/v3/api-docs
        name: 'camel-rest-client'
      - url: http://localhost:${server.port}/services/webflux-camel-rest-client-docs/v3/api-docs
        name: 'webflux-camel-rest-client'
      - url: http://localhost:${server.port}/services/webflux-rest-client-docs/v3/api-docs
        name: 'webflux-rest-client'
      - url: http://localhost:${server.port}/services/webflux-camel-soap-client-docs/v3/api-docs
        name: 'webflux-camel-soap-client'
      - url: http://localhost:${server.port}/services/spring-rest-client-docs/v3/api-docs
        name: 'spring-rest-client'
      - url: http://localhost:${server.port}/services/spring-rest-client-docs/v3/api-docs
        name: 'spring-webservices-soap-client'

    oauth:
      app-name: saber-client
      client-id: saber-client
      realm: saber66
      client-secret: 73b6e1da-d0ef-474c-97ae-d1c4438a7535
      scopes:
        - "openid"
        - "read"
        - "write"
    tags-sorter: alpha
  oAuthFlow:
    authorizationUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/auth
    tokenUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true
  api-docs:
    groups:
      enabled: true



hawtio:
  authenticationEnabled: false
management:
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      sla:
        "[http.server.requests]": 10ms, 100ms
      percentiles:
        "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuators/api-gateway
      exposure:
        include: '*'

