server:
  port: 9096
  max-http-header-size: 512000
  netty:
    connection-timeout: 10000
    idle-timeout: 10000
    threads: 3000
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        consistency-mode: consistent
        service-name: ${spring.application.name}
        hostname: localhost
    gateway:
      httpclient:
        pool:
          type: elastic
          max-idle-time: 10000
          max-connections: 5000
          max-life-time: 10000
        connect-timeout: 10000
        response-timeout: 30000
        max-header-size: 512000
      metrics:
        enabled: true
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: person-soap-client
          uri: lb://person-soap-client
          predicates:
            - Path=/services/person-soap-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: person-soap-client-docs
          uri: lb://person-soap-client
          predicates:
            - Path=/services/person-soap-client-docs/v2/api-docs

        - id: spring-camel-rest-client
          uri: lb://spring-camel-rest-client
          predicates:
            - Path=/services/camel-rest-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: spring-camel-rest-client-docs
          uri: lb://spring-camel-rest-client
          predicates:
            - Path=/services/camel-rest-client/v3/api-docs


        - id: webflux-camel-rest-client
          uri: lb://webflux-camel-rest-client
          predicates:
            - Path=/services/webflux-camel-rest-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: webflux-camel-rest-client-docs
          uri: lb://webflux-camel-rest-client
          predicates:
            - Path=/services/webflux-camel-rest-client-docs/v3/api-docs


        - id: spring-webflux-rest-client
          uri: lb://spring-webflux-rest-client
          predicates:
            - Path=/services/webflux-rest-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: spring-webflux-rest-client-docs
          uri: lb://spring-webflux-rest-client
          predicates:
            - Path=/services/webflux-rest-client-docs/v3/api-docs

        - id: webflux-camel-soap-client
          uri: lb://webflux-camel-soap-client
          predicates:
            - Path=/services/webflux-camel-soap-client/**
            - Method=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD,TRACE

        - id: webflux-camel-soap-client-docs
          uri: lb://webflux-camel-soap-client
          predicates:
            - Path=/services/webflux-camel-soap-client-docs/v3/api-docs


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    display-operation-id: true
    urls:
      - url: http://localhost:${server.port}/services/person-soap-client-docs/v2/api-docs
        name: 'spring camel soap client'
      - url: http://localhost:${server.port}/services/camel-rest-client/v3/api-docs
        name: 'camel-rest-client'
      - url: http://localhost:${server.port}/services/webflux-camel-rest-client-docs/v3/api-docs
        name: 'webflux-camel-rest-client'
      - url: http://localhost:${server.port}/services/webflux-rest-client-docs/v3/api-docs
        name: 'webflux-rest-client'
      - url: http://localhost:${server.port}/services/webflux-camel-soap-client-docs/v3/api-docs
        name: 'webflux-camel-soap-client'

  api-docs:
    groups:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
