server:
  port: 9091
  servlet:
    session:
      cookie:
        http-only: true
      timeout: 15
    encoding:
      force: true
      charset: UTF-8
  jetty:
    accesslog:
      enabled: true
    threads:
      max: 4000
      min: 400
      acceptors: 400
      selectors: 400
      max-queue-capacity: 2000
    max-http-form-post-size: 10
  max-http-header-size: 512000


service:
  api:
    path: /services/person-client
  swagger:
    path: '/services/person-client-docs/v2/api-docs'
    title: 'Person Client Service APi'
    version: 'version1.3-1400/11/01'
    description: 'This is person client api for test'

  person-api:
    serviceUrl: https://localhost:9090/soapServices/personSoap
    disableHostnameCheck: true
    connectTimeout: 30000
    readTimeout: 30000
    jksFile: person_api.jks
    jksPassword: saber@123
    username: saber66
    password: saber@123

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    display-operation-id: true
    persist-authorization: true
    operations-sorter: method

  api-docs:
    groups:
      enabled: true
    path: ${service.swagger.path}


spring:
  application:
    name: person-service

camel:
  springboot:
    route-controller-thread-pool-size: 30000
    jmx-management-statistics-level: extended
    consumer-template-cache-size: 15000
    producer-template-cache-size: 15000
    backlog-tracing: true
  dataformat:
    json-jackson:
      pretty-print: true
      auto-discover-object-mapper: true


hawtio:
  authenticationEnabled: false
management:
  metrics:
  distribution:
    percentiles-histogram:
      "[http.server.requests]": true
    sla:
      "[http.server.requests]": 10ms, 100ms
    percentiles:
      "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuators/person-client-api
      exposure:
        include: '*'

