server:
  port: 9092
  servlet:
    encoding:
      force: true
      charset: UTF-8
  jetty:
    accesslog:
      enabled: true
    threads:
      max: 3000
      min: 300
      idle-timeout: 10000
    connection-idle-timeout: 10000
  max-http-header-size: 512000


service:
  api:
    path: /services/person-soap-client
  swagger:
    path: '/services/person-soap-client-docs/v2/api-docs'
    title: 'Person Client Service API'
    version: 'version1.3-1400/12/11'
    description: 'This is person client api for test'
    host: 'localhost'
    api-gateway:
       host: 'localhost'
       port: 9096

  person-api:
    serviceUrl: https://localhost:9091/soapServices/personSoap
    disableHostnameCheck: true
    connectTimeout: 30000
    readTimeout: 30000
    jksFile: person_api.jks
    jksPassword: saber@123
    username: saber66
    password: saber@123


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    display-operation-id: true
    persist-authorization: true
    operations-sorter: method
  api-docs:
    groups:
      enabled: true
    path: ${service.swagger.path}
  oAuthFlow:
    authorizationUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/auth
    tokenUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true


spring:
  application:
    name: person-soap-client

camel:
  springboot:
    jmx-management-statistics-level: extended
    producer-template-cache-size: 5000
    backlog-tracing: true
  cloud:
    consul:
      service-host: localhost
      url: http://localhost:8500
      id: ${spring.application.name}
      registrationScheduled: 30000
    service-call:
      default-load-balancer: true
  dataformat:
    json-jackson:
      pretty-print: true
      auto-discover-object-mapper: true


hawtio:
  authenticationEnabled: false
management:
  metrics:
  distribution:
    percentiles-histogram:
      "[http.server.requests]": true
    sla:
      "[http.server.requests]": 10ms, 100ms
    percentiles:
      "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuators/person-client-api
      exposure:
        include: '*'

