
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.saber.spring_camel_cxf_client.dto.soap;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-06T17:10:43.907+03:30
 * Generated source version: 3.5.0
 *
 */

@WebService(
                      serviceName = "PersonSoapService",
                      portName = "personSoapApi",
                      targetNamespace = "http://services.soap.spring_camel_cxf_soap_provider.saber.com/",
                      wsdlLocation = "file:/C:/Users/azizi.s/AppData/Local/Temp/tempdir2240016499295246797.tmp/personSoap_1.wsdl",
                      endpointInterface = "com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService")

public class PersonSoapApiImpl implements PersonSoapService {

    private static final Logger LOG = Logger.getLogger(PersonSoapApiImpl.class.getName());

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#findAll()*
     */
    public FindAllPersonsResponse findAll() {
        LOG.info("Executing operation findAll");
        try {
            FindAllPersonsResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#deletePersonByNationalCode(java.lang.String nationalCode)*
     */
    public DeletePersonResponse deletePersonByNationalCode(String nationalCode) {
        LOG.info("Executing operation deletePersonByNationalCode");
        System.out.println(nationalCode);
        try {
            DeletePersonResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#findByNationalCode(java.lang.String nationalCode)*
     */
    public PersonSoapResponse findByNationalCode(String nationalCode) {
        LOG.info("Executing operation findByNationalCode");
        System.out.println(nationalCode);
        try {
            PersonSoapResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#addPerson(com.saber.spring_camel_cxf_client.dto.soap.PersonSoapDto personSoapDto)*
     */
    public AddPersonResponseDto addPerson(PersonSoapDto personSoapDto) {
        LOG.info("Executing operation addPerson");
        System.out.println(personSoapDto);
        try {
            AddPersonResponseDto _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#updatePersonByNationalCode(java.lang.String nationalCode, com.saber.spring_camel_cxf_client.dto.soap.PersonSoapDto personDto)*
     */
    public UpdatePersonResponse updatePersonByNationalCode(String nationalCode, PersonSoapDto personDto) {
        LOG.info("Executing operation updatePersonByNationalCode");
        System.out.println(nationalCode);
        System.out.println(personDto);
        try {
            UpdatePersonResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
