
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.saber.spring_camel_cxf_client.dto.soap;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-01-21T22:22:58.630+03:30
 * Generated source version: 3.4.4
 *
 */

@WebService(
                      serviceName = "PersonSoapService",
                      portName = "PersonSoapServicePort",
                      targetNamespace = "http://soap.spring_camel_service_provider.saber.com/",
                      wsdlLocation = "file:/C:/Users/SABER/AppData/Local/Temp/tempdir12693652314229710864.tmp/personSoap_1.wsdl",
                      endpointInterface = "com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService")

public class PersonSoapServicePortImpl implements PersonSoapService {

    private static final Logger LOG = Logger.getLogger(PersonSoapServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#addPerson(com.saber.spring_camel_cxf_client.dto.soap.AddPerson parameters, com.saber.spring_camel_cxf_client.dto.soap.AuthHeader authHeader)*
     */
    public AddPersonResponse addPerson(AddPerson parameters, AuthHeader authHeader) {
        LOG.info("Executing operation addPerson");
        System.out.println(parameters);
        System.out.println(authHeader);
        try {
            AddPersonResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#updatePersonByNationalCode(com.saber.spring_camel_cxf_client.dto.soap.UpdatePersonByNationalCode parameters, com.saber.spring_camel_cxf_client.dto.soap.AuthHeader authHeader)*
     */
    public UpdatePersonByNationalCodeResponse updatePersonByNationalCode(UpdatePersonByNationalCode parameters, AuthHeader authHeader) {
        LOG.info("Executing operation updatePersonByNationalCode");
        System.out.println(parameters);
        System.out.println(authHeader);
        try {
            UpdatePersonByNationalCodeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#findByNationalCode(com.saber.spring_camel_cxf_client.dto.soap.FindByNationalCode parameters, com.saber.spring_camel_cxf_client.dto.soap.AuthHeader authHeader)*
     */
    public FindByNationalCodeResponse findByNationalCode(FindByNationalCode parameters, AuthHeader authHeader) {
        LOG.info("Executing operation findByNationalCode");
        System.out.println(parameters);
        System.out.println(authHeader);
        try {
            FindByNationalCodeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#deletePersonByNationalCode(com.saber.spring_camel_cxf_client.dto.soap.DeletePersonByNationalCode parameters, com.saber.spring_camel_cxf_client.dto.soap.AuthHeader authHeader)*
     */
    public DeletePersonByNationalCodeResponse deletePersonByNationalCode(DeletePersonByNationalCode parameters, AuthHeader authHeader) {
        LOG.info("Executing operation deletePersonByNationalCode");
        System.out.println(parameters);
        System.out.println(authHeader);
        try {
            DeletePersonByNationalCodeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.saber.spring_camel_cxf_client.dto.soap.PersonSoapService#findAll(com.saber.spring_camel_cxf_client.dto.soap.FindAll parameters, com.saber.spring_camel_cxf_client.dto.soap.AuthHeader authHeader)*
     */
    public FindAllResponse findAll(FindAll parameters, AuthHeader authHeader) {
        LOG.info("Executing operation findAll");
        System.out.println(parameters);
        System.out.println(authHeader);
        try {
            FindAllResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
