
package com.saber.spring_camel_cxf_client.dto.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-01-22T13:01:50.819+03:30
 * Generated source version: 3.5.0
 *
 */
public final class PersonSoapService_PersonSoapServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.spring_camel_service_provider.saber.com/", "PersonSoapService");

    private PersonSoapService_PersonSoapServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PersonSoapService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PersonSoapService_Service ss = new PersonSoapService_Service(wsdlURL, SERVICE_NAME);
        PersonSoapService port = ss.getPersonSoapServicePort();

        {
        System.out.println("Invoking addPerson...");
        AuthHeader _addPerson_authHeader = null;
        PersonSoapDto _addPerson_personSoapDto = null;
        PersonSoapResponse _addPerson__return = port.addPerson(_addPerson_authHeader, _addPerson_personSoapDto);
        System.out.println("addPerson.result=" + _addPerson__return);


        }
        {
        System.out.println("Invoking updatePersonByNationalCode...");
        AuthHeader _updatePersonByNationalCode_authHeader = null;
        String _updatePersonByNationalCode_nationalCode = "";
        PersonSoapDto _updatePersonByNationalCode_personDto = null;
        PersonSoapResponse _updatePersonByNationalCode__return = port.updatePersonByNationalCode(_updatePersonByNationalCode_authHeader, _updatePersonByNationalCode_nationalCode, _updatePersonByNationalCode_personDto);
        System.out.println("updatePersonByNationalCode.result=" + _updatePersonByNationalCode__return);


        }
        {
        System.out.println("Invoking findByNationalCode...");
        AuthHeader _findByNationalCode_authHeader = null;
        String _findByNationalCode_nationalCode = "";
        PersonSoapResponse _findByNationalCode__return = port.findByNationalCode(_findByNationalCode_authHeader, _findByNationalCode_nationalCode);
        System.out.println("findByNationalCode.result=" + _findByNationalCode__return);


        }
        {
        System.out.println("Invoking deletePersonByNationalCode...");
        AuthHeader _deletePersonByNationalCode_authHeader = null;
        String _deletePersonByNationalCode_nationalCode = "";
        DeletePersonResponse _deletePersonByNationalCode__return = port.deletePersonByNationalCode(_deletePersonByNationalCode_authHeader, _deletePersonByNationalCode_nationalCode);
        System.out.println("deletePersonByNationalCode.result=" + _deletePersonByNationalCode__return);


        }
        {
        System.out.println("Invoking findAll...");
        AuthHeader _findAll_authHeader = null;
        FindAllPersonsResponse _findAll__return = port.findAll(_findAll_authHeader);
        System.out.println("findAll.result=" + _findAll__return);


        }

        System.exit(0);
    }

}
