package com.saber.spring_camel_cxf_client.dto.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-01-21T22:22:58.661+03:30
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", name = "PersonSoapService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PersonSoapService {

    @WebMethod(operationName = "AddPerson", action = "AddPerson")
    @WebResult(name = "AddPersonResponse", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", partName = "parameters")
    public AddPersonResponse addPerson(

        @WebParam(partName = "parameters", name = "AddPerson", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/")
        AddPerson parameters,
        @WebParam(partName = "AuthHeader", name = "AuthHeader", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", header = true)
        AuthHeader authHeader
    );

    @WebMethod(operationName = "UpdatePersonByNationalCode", action = "UpdatePersonByNationalCode")
    @WebResult(name = "UpdatePersonByNationalCodeResponse", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", partName = "parameters")
    public UpdatePersonByNationalCodeResponse updatePersonByNationalCode(

        @WebParam(partName = "parameters", name = "UpdatePersonByNationalCode", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/")
        UpdatePersonByNationalCode parameters,
        @WebParam(partName = "AuthHeader", name = "AuthHeader", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", header = true)
        AuthHeader authHeader
    );

    @WebMethod(operationName = "FindByNationalCode", action = "FindByNationalCode")
    @WebResult(name = "FindByNationalCodeResponse", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", partName = "parameters")
    public FindByNationalCodeResponse findByNationalCode(

        @WebParam(partName = "parameters", name = "FindByNationalCode", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/")
        FindByNationalCode parameters,
        @WebParam(partName = "AuthHeader", name = "AuthHeader", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", header = true)
        AuthHeader authHeader
    );

    @WebMethod(operationName = "DeletePersonByNationalCode", action = "DeletePersonByNationalCode")
    @WebResult(name = "DeletePersonByNationalCodeResponse", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", partName = "parameters")
    public DeletePersonByNationalCodeResponse deletePersonByNationalCode(

        @WebParam(partName = "parameters", name = "DeletePersonByNationalCode", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/")
        DeletePersonByNationalCode parameters,
        @WebParam(partName = "AuthHeader", name = "AuthHeader", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", header = true)
        AuthHeader authHeader
    );

    @WebMethod(operationName = "FindAll", action = "FindAll")
    @WebResult(name = "FindAllResponse", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", partName = "parameters")
    public FindAllResponse findAll(

        @WebParam(partName = "parameters", name = "FindAll", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/")
        FindAll parameters,
        @WebParam(partName = "AuthHeader", name = "AuthHeader", targetNamespace = "http://soap.spring_camel_service_provider.saber.com/", header = true)
        AuthHeader authHeader
    );
}
