
package com.saber.spring_camel_cxf_client.dto.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-06T17:10:43.860+03:30
 * Generated source version: 3.5.0
 *
 */
public final class PersonSoapService_PersonSoapApi_Client {

    private static final QName SERVICE_NAME = new QName("http://services.soap.spring_camel_cxf_soap_provider.saber.com/", "PersonSoapService");

    private PersonSoapService_PersonSoapApi_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PersonSoapService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PersonSoapService_Service ss = new PersonSoapService_Service(wsdlURL, SERVICE_NAME);
        PersonSoapService port = ss.getPersonSoapApi();

        {
        System.out.println("Invoking findAll...");
        FindAllPersonsResponse _findAll__return = port.findAll();
        System.out.println("findAll.result=" + _findAll__return);


        }
        {
        System.out.println("Invoking deletePersonByNationalCode...");
        String _deletePersonByNationalCode_nationalCode = "";
        DeletePersonResponse _deletePersonByNationalCode__return = port.deletePersonByNationalCode(_deletePersonByNationalCode_nationalCode);
        System.out.println("deletePersonByNationalCode.result=" + _deletePersonByNationalCode__return);


        }
        {
        System.out.println("Invoking findByNationalCode...");
        String _findByNationalCode_nationalCode = "";
        PersonSoapResponse _findByNationalCode__return = port.findByNationalCode(_findByNationalCode_nationalCode);
        System.out.println("findByNationalCode.result=" + _findByNationalCode__return);


        }
        {
        System.out.println("Invoking addPerson...");
        PersonSoapDto _addPerson_personSoapDto = null;
        AddPersonResponseDto _addPerson__return = port.addPerson(_addPerson_personSoapDto);
        System.out.println("addPerson.result=" + _addPerson__return);


        }
        {
        System.out.println("Invoking updatePersonByNationalCode...");
        String _updatePersonByNationalCode_nationalCode = "";
        PersonSoapDto _updatePersonByNationalCode_personDto = null;
        UpdatePersonResponse _updatePersonByNationalCode__return = port.updatePersonByNationalCode(_updatePersonByNationalCode_nationalCode, _updatePersonByNationalCode_personDto);
        System.out.println("updatePersonByNationalCode.result=" + _updatePersonByNationalCode__return);


        }

        System.exit(0);
    }

}
