server:
  port: 9095
  netty:
    connection-timeout: 10000
    idle-timeout: 10000
    threads: 3000

service:
  api:
    base-path: /services/webflux-camel-rest-client
  person:
    url: https://localhost
    port: 9090
    baseUrl : /services/person
    findAll: /findAll
    findByNationalCode: /find
    addPerson: /add
    updatePerson: /update
    deletePerson: /delete

  swagger:
    path: /services/webflux-camel-rest-client-docs/v3/api-docs
    version: 'version1.0.0-1400/12/08'
    title: 'webflux-camel-rest-client'
    description: 'webflux-camel-rest-client'
    host: 'localhost'
    api-gateway:
      host: 'localhost'
      port: 9096

  keystore:
    jksFile: 'keystore/person_api.jks'
    jksPassword: saber@123
  authorization:
    username: saber66
    password: saber@123



camel:
  springboot:
    main-run-controller: true
    jmx-management-statistics-level: extended
    endpoint-runtime-statistics-enabled: true
    jmx-enabled: true
    producer-template-cache-size: 5000
  cloud:
    consul:
      service-host: localhost
      url: http://localhost:8500
      id: ${spring.application.name}
      registrationScheduled: 30000
    service-call:
      default-load-balancer: true
  component:
    http:
      connections-per-route: 300
      max-total-connections: 3000
      connect-timeout: 5000
      socket-timeout: 30000
      connection-request-timeout: 30000
      connection-time-to-live: 10000
  dataformat:
    jackson:
      auto-discover-object-mapper: true

spring:
  application:
    name: webflux-camel-rest-client

springdoc:
  swagger-ui:
    display-operation-id: true
    display-request-duration: true
    path: /swagger-ui.html

  api-docs:
    groups:
      enabled: true
    path:  ${service.swagger.path}
  oAuthFlow:
    authorizationUrl: http://localhost:8080/auth/realms/keycloak/protocol/openid-connect/auth
    tokenUrl: http://localhost:8080/auth/realms/keycloak/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true

hawtio:
  authenticationEnabled: false
management:
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      sla:
        "[http.server.requests]": 10ms, 100ms
      percentiles:
        "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  #    export:
  #      jmx:
  #        domain: hawtio
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuators/webflux-camel-rest-client
  enabled: false
  health: true
