server:
  port: 9093
  max-http-header-size: 512000
  netty:
    connection-timeout: 10000
    idle-timeout: 10000
    threads: 3000
service:
  api:
    base-path: /services/webflux-rest-client
  person:
    url: https://localhost
    port: 9090
    baseUrl : /services/person
    findAll: /findAll
    findByNationalCode: /find
    addPerson: /add
    updatePerson: /update
    deletePerson: /delete
    timeout: 30000
    maxConnection: 500
  swagger:
    path: /services/webflux-rest-client-docs/v3/api-docs
    version: 'version1.0.0-1400/12/11'
    title: 'webflux-rest-client'
    description: 'webflux-rest-client'
    host: 'localhost'
    api-gateway:
      host: 'localhost'
      port: 9096

  keystore:
    jksFile: 'keystore/person_api.jks'
    jksPassword: saber@123
  authorization:
    username: saber66
    password: saber@123



camel:
  springboot:
    main-run-controller: true
    jmx-management-statistics-level: extended
    endpoint-runtime-statistics-enabled: true
    jmx-enabled: true
  cloud:
    consul:
      service-host: localhost
      url: http://localhost:8500
      id: ${spring.application.name}
      registrationScheduled: 30000
    service-call:
      default-load-balancer: true


spring:
  application:
    name: spring-webflux-rest-client

springdoc:
  swagger-ui:
    display-operation-id: true
    display-request-duration: true
    path: /swagger-ui.html

  api-docs:
    groups:
      enabled: true
    path:  ${service.swagger.path}
  oAuthFlow:
    authorizationUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/auth
    tokenUrl: http://localhost:7080/auth/realms/saber66/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
